# Generated by Django 5.0 on 2025-11-20 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('function_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genes',
            },
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.BigIntegerField()),
                ('reference_base', models.CharField(max_length=500)),
                ('alternate_base', models.CharField(max_length=500)),
                ('impact', models.CharField(choices=[('Missense', 'Missense'), ('Nonsense', 'Nonsense'), ('Frameshift', 'Frameshift'), ('Silent', 'Silent'), ('Splice Site', 'Splice Site'), ('Otros', 'Otros')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.gene')),
            ],
            options={
                'db_table': 'genetic_variants',
            },
        ),
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('detection_date', models.DateField()),
                ('allele_frequency', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.geneticvariant')),
            ],
            options={
                'db_table': 'patient_variant_reports',
            },
        ),
    ]
